image:
  name: gitlab-registry.dubzland.net/holodekk/rust-docker-ci:latest

stages:
  - lint
  - test
  - build

default:
  cache: &global_cache
    key:
      files:
        - Cargo.lock
    paths:
      - cargo/
      - target/
    policy: pull-push

variables:
  CARGO_HOME: $CI_PROJECT_DIR/cargo
  DOCKER_TLS_CERTDIR: "/certs"

clippy:
  stage: lint
  cache:
    <<: *global_cache
    key:
      files:
        - Cargo.lock
      prefix: clippy
    when: 'always'
  before_script:
    - rustc --version
    - cargo --version
    - protoc --version
  script:
    - cargo clippy --verbose

test:
  stage: test
  cache:
    <<: *global_cache
    key:
      files:
        - Cargo.lock
      prefix: test
  services:
    # Use alternate dind image
    # see here: https://gitlab.com/gitlab-org/gitlab-runner/-/issues/29130#note_1075191809
    # - name: docker:23.0.1-dind
    - name: ${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/serversideup/docker-utility
      alias: docker
    - name: ${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/registry
  variables:
    DOCKER_HOST: "https://docker:2376"
    DOCKER_CERT_PATH: "/certs/client"

  before_script:
    - rustc --version
    - cargo --version
  script:
    - cargo test --verbose

build:
  stage: build
  cache:
    <<: *global_cache
    key:
    key:
      files:
        - Cargo.lock
      prefix: build
  before_script:
    - rustc --version
    - cargo --version
  script:
    - cargo build
