image:
  name: ${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/dubzland/ci-rust:1.1.0

stages:
  - test
  - lint
  - build

cache: &global_cache
  key:
    files:
      - Cargo.lock
  paths:
    - .cargo/.crates.toml
    - .cargo/.crates2.json
    - .cargo/bin/
    - .cargo/registry/index/
    - .cargo/registry/cache/
    - .cargo/git/db/
    - target/debug/deps
    - target/debug/build
  policy: pull-push

variables:
  CARGO_HOME: $CI_PROJECT_DIR/.cargo
  DOCKER_TLS_CERTDIR: "/certs"

test:
  stage: test
  services:
    # Use alternate dind image
    # see here: https://gitlab.com/gitlab-org/gitlab-runner/-/issues/29130#note_1075191809
    # - name: docker:23.0.1-dind
    - name: ${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/serversideup/docker-utility
      alias: docker
    - name: ${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/registry
  variables:
    DOCKER_HOST: "https://docker:2376"
    DOCKER_CERT_PATH: "/certs/client"

  before_script:
    - rustc --version
    - cargo --version
  script:
    - cargo test --verbose

clippy:
  stage: lint
  cache:
    <<: *global_cache
    policy: pull
  before_script:
    - rustc --version
    - cargo --version
    - protoc --version
  script:
    - cargo clippy --verbose

build:
  stage: build
  cache:
    <<: *global_cache
    policy: pull
  before_script:
    - rustc --version
    - cargo --version
  script:
    - cargo build
