[workspace]
members = [
    "crates/holodekk-cli",
    "crates/holodekkd",
    "crates/holodekk-core",
    "crates/holodekk-projector",
    "crates/holodekk-shim",
]

[workspace.package]
version = "0.1.0"
edition = "2021"
repository = "https://git.dubzland.net/holodekk/holodekk"
license = "MIT"
license-file = "LICENSE"

# # See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace.dependencies]
holodekk-core = { path = "./crates/holodekk-core" }
holodekk-projector = { path = "./crates/holodekk-projector" }
clap = { version = "4.1.6", features = ["derive"] }
serde = { version = "1.0.152", features = ["derive"] }
serde_json = "1.0.93"
tokio = { version = "1.26.0", features = ["full"] }
