[package]
name = "holodekk"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-http = "3.3.1"
actix-web = "4"
async-stream = "0.3.4"
awc = "3.1.1"
awc-uds = "0.1.1"
buildkit-llb = "0.2.0"
clap = { version = "4.1.6", features = ["derive"] }
flate2 = "1.0.25"
futures = "0.3.26"
hyper = "0.14.24"
hyperlocal = "0.8.0"
libc = "0.2.139"
log = "0.4.17"
nix = "0.26.2"
pipe = "0.4.0"
serde = { version = "1.0.152", features = ["derive"] }
serde_json = "1.0.93"
syslog = "6.0.1"
tar = "0.4.38"
tokio = { version = "1.26.0", features = ["full"] }
tokio-stream = "0.1.12"
users = "0.11.0"
