[workspace]
members = [
    "crates/holodekkd",
    "crates/holodekk-cli",
    "crates/holodekk-core",
    "crates/holodekk-projector",
    "crates/holodekk-shim",
    "crates/holodekk-subroutine",
    "uhura"
]

[workspace.package]
version = "0.1.0"
edition = "2021"
repository = "https://git.dubzland.net/holodekk/holodekk"
license = "MIT"
license-file = "LICENSE"

[workspace.dependencies]
async-trait = "0.1.67"
holodekk = { path = "./crates/holodekk-core" }
holodekk-projector = { path = "./crates/holodekk-projector" }
clap = { version = "4.1.6", features = ["derive"] }
futures-util = "0.3.27"
libc = "0.2.139"
log = "0.4.17"
mio = "0.8.6"
nix = "0.26.2"
serde = { version = "1.0.152", features = ["derive"] }
serde_json = "1.0.93"
syslog = "6.0.1"
thiserror = "1.0.40"
tokio = { version = "1.26.0", features = ["full"] }
