[package]
name = "holodekk"
version.workspace = true
edition.workspace = true
repository.workspace = true
license-file.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap.workspace = true
futures-util.workspace = true
log.workspace = true
mio.workspace = true
serde.workspace = true
serde_json.workspace = true
syslog.workspace = true
tokio.workspace = true
actix-web = "4"
async-trait = "0.1.67"
bollard = "0.14.0"
flate2 = "1.0.25"
futures = "0.3.27"
hyper = "0.14.24"
hyperlocal = "0.8.0"
libc = "0.2.139"
prost = "0.11.8"
regex = "1.7.1"
tar = "0.4.38"
thiserror = "1.0.40"
tonic = "0.8.3"

[build-dependencies]
tonic-build = "0.8.4"
