[package]
name = "holodekk-projector"
version.workspace = true
edition.workspace = true
repository.workspace = true
license-file.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio.workspace = true
tonic = "0.8.3"
prost = "0.11.8"
futures-util = "0.3.27"
thiserror = "1.0.40"
futures = "0.3.27"

[build-dependencies]
tonic-build = "0.8.4"
