[package]
name = "holodekkd"
version.workspace = true
edition.workspace = true
repository.workspace = true
license-file.workspace = true

[dependencies]
clap.workspace = true
holodekk.workspace = true
tokio.workspace = true

[dev-dependencies]
tempfile = "3.4.0"
