[package]
name = "holodekkd"
version.workspace = true
edition.workspace = true
repository.workspace = true
license-file.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap.workspace = true
actix-http = "3.3.1"
actix-web = "4"
awc = "3.1.1"
awc-uds = "0.1.1"
nix = "0.26.2"
users = "0.11.0"
