[package]
name = "holodekkd"
version.workspace = true
edition.workspace = true
repository.workspace = true
license-file.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap.workspace = true
serde.workspace = true
serde_json.workspace = true
actix-http = "3.3.1"
actix-web = "4"
async-stream = "0.3.4"
awc = "3.1.1"
awc-uds = "0.1.1"
bollard = "0.14.0"
futures-util = "0.3.27"
magnus = { version = "0.5.1", features = ["embed"] }
nix = "0.26.2"
tokio = { version = "1.26.0", features = ["full"] }
tokio-stream = "0.1.12"
users = "0.11.0"
